# Generated by Django 4.2 on 2023-05-15 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_sell_post_options_sell_post_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
