# Generated by Django 4.2 on 2023-05-15 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_tag_is_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-created_date']},
        ),
    ]
