# Generated by Django 4.2 on 2023-05-15 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_remove_forumcomment_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reply',
            name='created_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='sell_post',
            name='created_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='sell_post_category',
            name='created_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tag',
            name='created_date',
            field=models.DateTimeField(),
        ),
    ]
