# Generated by Django 4.2 on 2023-05-15 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_blog_created_date_alter_category_created_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sell_post',
            name='is_featured',
        ),
    ]
