# Generated by Django 4.2 on 2023-05-07 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellposts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Sell_Post_Category',
        ),
    ]
